sudo: false
language: python
env:
  - DJANGO=1.7.11 TEST_DIR=jalali_test
  - DJANGO=1.8.8 TEST_DIR=jalali_test
  - DJANGO=1.9.0 TEST_DIR=jalali_test
  - DJANGO=1.9.1 TEST_DIR=jalali_test
  - DJANGO=1.9.5 TEST_DIR=jalali_test
  - DJANGO=1.10 TEST_DIR=jalali_test
  - DJANGO=2.0 TEST_DIR=jalali_test_2_0
python:
  - 2.7
  - 3.4
  - 3.6
matrix:
  allow_failures:
    - python: 3.6
      env: DJANGO=1.7.11 TEST_DIR=jalali_test
    - python: 2.7
      env: DJANGO=2.0 TEST_DIR=jalali_test_2_0
install:
  - pip install -q Django==$DJANGO
  - pip install jdatetime
before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
script:
  - cd $TEST_DIR
  - python manage.py test
  - cd ..
  - python setup.py sdist
  - pip install dist/django-jalali*
matrix:
  exclude:
  - env: DJANGO=1.7.11
    python: "3.6"
  - env: DJANGO=1.7.11
    python: "3.5"